// AUTO-GENERATED by scripts/build_store.py — do not edit by hand.
// Regenerate after editing store/signals.jsonl or funds.json.
window.__STORE__ = {
  "generated_at": "2026-07-16T14:53:23Z",
  "signal_count": 14,
  "signals": [
    {
      "signal_id": "sig_call_503460551892",
      "engagement_id": "503460551892",
      "engagement_type": "call",
      "engagement_title": "Call with Moonfare: Nicolas Hentgen",
      "timestamp": "2026-07-14T12:14:28Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503460551892",
      "contact": {
        "id": null,
        "name": "Nicolas Hentgen",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Ethan Dabush",
      "interest_level": "hot",
      "sentiment": "positive",
      "sentiment_score": 0.7,
      "urgency": "high",
      "asset_classes": [
        "Venture Capital",
        "Direct Deal"
      ],
      "industries": [
        "Technology",
        "AI",
        "Cybersecurity"
      ],
      "funds": [
        {
          "raw": "Moonfair Tech Fund",
          "canonical": "Moonfare Tech Fund",
          "fund_id": "moonfare_tech_fund",
          "asset_class": "Venture Capital",
          "match": "alias",
          "confidence": 0.97
        }
      ],
      "competitors_mentioned": [
        "Hamilton Lane",
        "StepStone"
      ],
      "ticket_size": {
        "raw": "personal ticket €200k–500k; family-office program envelope €3M",
        "amount_eur": null,
        "min": 200000,
        "max": 500000,
        "currency": "EUR",
        "basis": "range",
        "confidence": 0.85
      },
      "pain_points": [
        "high entry valuations"
      ],
      "objections": [],
      "next_step": "Nicolas to present venture options to his board; follow-up on family + professional commitments",
      "next_step_date": "2026-07-24",
      "quotes": [
        "Family office program has a total envelope of 3 million euros",
        "Personal ticket sizes between 200,000 and 500,000 euros",
        "Evaluating Hamilton Lane and StepStone alongside Moonfare",
        "Ethan stated a targeted 3x return"
      ],
      "summary": "Multi-source prospect (personal, family office €3M, employer) hot on the Moonfare Tech Fund; presenting to his board within ~10 days and comparing against Hamilton Lane and StepStone.",
      "source_excerpt": "Nicolas H. and Ethan Dabush discussed opportunities through Moonfare; multiple funding avenues; Moonfare Tech Fund targets top-tier venture with smaller ticket sizes; target 3x; evaluating Hamilton Lane and StepStone.",
      "extraction_confidence": 0.9,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_503296041170",
      "engagement_id": "503296041170",
      "engagement_type": "call",
      "engagement_title": "Dexter Tjoa and Ethan Dabush",
      "timestamp": "2026-07-13T13:00:13Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503296041170",
      "contact": {
        "id": null,
        "name": "Dexter Tjoa",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Ethan Dabush",
      "interest_level": "hot",
      "sentiment": "positive",
      "sentiment_score": 0.6,
      "urgency": "medium",
      "asset_classes": [
        "Buyout",
        "Multi-Strategy / Evergreen"
      ],
      "industries": [
        "Healthcare",
        "Europe"
      ],
      "funds": [
        {
          "raw": "EQT",
          "canonical": "EQT XI",
          "fund_id": "eqt_xi",
          "asset_class": "Buyout",
          "match": "alias",
          "confidence": 0.75
        },
        {
          "raw": "CVC",
          "canonical": "CVC-PE",
          "fund_id": "cvc_pe",
          "asset_class": "Buyout",
          "match": "fuzzy",
          "confidence": 0.55
        }
      ],
      "competitors_mentioned": [],
      "ticket_size": {
        "raw": "around 300K in private equity",
        "amount_eur": 300000,
        "min": null,
        "max": null,
        "currency": "EUR",
        "basis": "stated",
        "confidence": 0.7
      },
      "pain_points": [
        "high or unclear fees",
        "onboarding / verification friction"
      ],
      "objections": [
        "wants to do own research before committing"
      ],
      "next_step": "Ethan to send fund information and resources; Dexter to research EQT and CVC",
      "next_step_date": null,
      "quotes": [
        "Looking to invest around 300K, focus on healthcare and European opportunities",
        "1% setup fee plus ongoing management fees",
        "EQT and CVC highlighted as key opportunities",
        "Has not completed onboarding yet"
      ],
      "summary": "~€300k prospect focused on healthcare / European buyout, interested in EQT and CVC; comfortable with requirements but not yet onboarded and will research before committing.",
      "source_excerpt": "Ethan Dabush and Dexter discussed direct and evergreen funds, fee structures, onboarding; Dexter targets ~300K healthcare/European PE; EQT and CVC highlighted.",
      "extraction_confidence": 0.88,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_503270099138",
      "engagement_id": "503270099138",
      "engagement_type": "call",
      "engagement_title": "Call with Moonfare: Andreas Bäcker",
      "timestamp": "2026-07-13T11:30:06Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503270099138",
      "contact": {
        "id": null,
        "name": "Andreas Bäcker",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Kyra Thoma",
      "interest_level": "warm",
      "sentiment": "positive",
      "sentiment_score": 0.5,
      "urgency": "medium",
      "asset_classes": [
        "Venture Capital",
        "Buyout",
        "Direct Deal"
      ],
      "industries": [],
      "funds": [
        {
          "raw": "Moonfair Tech Fund",
          "canonical": "Moonfare Tech Fund",
          "fund_id": "moonfare_tech_fund",
          "asset_class": "Venture Capital",
          "match": "alias",
          "confidence": 0.97
        }
      ],
      "competitors_mentioned": [],
      "ticket_size": {
        "raw": "open to investing 250,000 euros or more",
        "amount_eur": null,
        "min": 250000,
        "max": null,
        "currency": "EUR",
        "basis": "stated",
        "confidence": 0.8
      },
      "pain_points": [
        "high or unclear fees"
      ],
      "objections": [],
      "next_step": "Kyra to send cost-structure and fund information; follow-up call scheduled Thursday",
      "next_step_date": null,
      "quotes": [
        "Open to investing 250,000 euros or more in private equity",
        "Moonfare Tech Fund with a target of 3x returns",
        "1% initial fee and management fees based on investment amount"
      ],
      "summary": "Intro call: prospect open to €250k+ in private equity, interested in Moonfare Tech Fund (3x target); follow-up scheduled to go deeper on funds and costs.",
      "source_excerpt": "Kyra Thoma introduced Moonfare; prospect open to 250k+; Moonfare Tech Fund 3x; fee structure 1% initial + management fees; follow-up Thursday.",
      "extraction_confidence": 0.87,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_503971285218",
      "engagement_id": "503971285218",
      "engagement_type": "call",
      "engagement_title": "Moonfare Follow-up | Andreas Bäcker <> Kyra Thoma",
      "timestamp": "2026-07-16T11:59:56Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503971285218",
      "contact": {
        "id": null,
        "name": "Andreas Bäcker",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Kyra Thoma",
      "interest_level": "warm",
      "sentiment": "mixed",
      "sentiment_score": 0.2,
      "urgency": "medium",
      "asset_classes": [
        "Venture Capital",
        "Buyout"
      ],
      "industries": [],
      "funds": [
        {
          "raw": "Moonfair Tech Fund",
          "canonical": "Moonfare Tech Fund",
          "fund_id": "moonfare_tech_fund",
          "asset_class": "Venture Capital",
          "match": "alias",
          "confidence": 0.97
        }
      ],
      "competitors_mentioned": [],
      "ticket_size": {
        "raw": "€250k+ (per prior intro call)",
        "amount_eur": null,
        "min": 250000,
        "max": null,
        "currency": "EUR",
        "basis": "inferred",
        "confidence": 0.5
      },
      "pain_points": [
        "long commitment duration / illiquidity",
        "high or unclear fees",
        "risk / loss concerns",
        "capital-call timing / cash-flow profile"
      ],
      "objections": [
        "concern about the fund's long-term commitment duration"
      ],
      "next_step": "Address commitment-duration and fee concerns; continue evaluation",
      "next_step_date": null,
      "quotes": [
        "Expressed interest in investing but had concerns about the fund's long-term commitment duration",
        "Discussion on capital call timing, fee structures, and risk management"
      ],
      "summary": "Follow-up on the Moonfare Tech Fund: still interested but weighing long commitment duration, fees and risk — engaged but not yet committed.",
      "source_excerpt": "Kyra Thoma addressed questions on portfolio management, fee structures and risk; prospect interested but concerned about long-term commitment duration; capital-call timing and fees discussed.",
      "extraction_confidence": 0.85,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_503324555471",
      "engagement_id": "503324555471",
      "engagement_type": "call",
      "engagement_title": "Bénédicte / Ethan",
      "timestamp": "2026-07-13T15:00:47Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503324555471",
      "contact": {
        "id": null,
        "name": "Bénédicte",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Ethan Dabush",
      "interest_level": "existing_investor",
      "sentiment": "mixed",
      "sentiment_score": 0.2,
      "urgency": "high",
      "asset_classes": [
        "Venture Capital",
        "Direct Deal"
      ],
      "industries": [
        "AI"
      ],
      "funds": [
        {
          "raw": "Horovich fund",
          "canonical": null,
          "fund_id": null,
          "asset_class": null,
          "match": "unmatched",
          "confidence": 0.0
        },
        {
          "raw": "Databricks",
          "canonical": "Databricks",
          "fund_id": "databricks",
          "asset_class": "Direct Deal",
          "match": "exact",
          "confidence": 0.9
        }
      ],
      "competitors_mentioned": [],
      "ticket_size": {
        "raw": "considering increasing existing commitment",
        "amount_eur": null,
        "min": null,
        "max": null,
        "currency": null,
        "basis": "threshold_discussed",
        "confidence": 0.3
      },
      "pain_points": [
        "high entry valuations"
      ],
      "objections": [
        "concern that high valuations affect investment attractiveness"
      ],
      "next_step": "Ethan to send fund investment and valuation details; Bénédicte to decide with Christoph before deadline",
      "next_step_date": "2026-08-15",
      "quotes": [
        "Considering increasing investment in the fund, which is nearly 50% deployed",
        "Concern about high valuations",
        "Decision deadline around mid-August",
        "Surge in venture fund activity, especially in AI"
      ],
      "summary": "Existing investor weighing a top-up into an AI-heavy venture fund (~50% deployed, Databricks among holdings); valuation-sensitive, decision due mid-August. Note: 'Horovich fund' unmatched — likely a transcription error, needs review.",
      "source_excerpt": "Ethan and Bénédicte discussed increasing commitment to a venture fund nearly 50% deployed; valuations at cost with exceptions (Databricks); decision deadline mid-August; AI venture interest surging.",
      "extraction_confidence": 0.8,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_503585083637",
      "engagement_id": "503585083637",
      "engagement_type": "call",
      "engagement_title": "Moonfare <> Paulo Marques",
      "timestamp": "2026-07-15T08:26:43Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503585083637",
      "contact": {
        "id": null,
        "name": "Paulo Marques",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Keistha Amanda Tanzil",
      "interest_level": "warm",
      "sentiment": "positive",
      "sentiment_score": 0.5,
      "urgency": "low",
      "asset_classes": [
        "Multi-Strategy / Evergreen",
        "Buyout"
      ],
      "industries": [],
      "funds": [],
      "competitors_mentioned": [],
      "ticket_size": {
        "raw": "platform minimums discussed: €25k evergreen / $125k third-party (not investor's own ticket)",
        "amount_eur": null,
        "min": null,
        "max": null,
        "currency": "EUR",
        "basis": "threshold_discussed",
        "confidence": 0.4
      },
      "pain_points": [
        "eligibility / professional-investor classification",
        "minimum ticket too high"
      ],
      "objections": [],
      "next_step": "Complete ID verification to access fund details; Keistha to send summary of available funds",
      "next_step_date": null,
      "quotes": [
        "New to private equity and wants to invest through Moonfare",
        "Needs to be classified as a professional investor",
        "Minimum for evergreen funds starts at €25,000; third-party funds usually require $125,000"
      ],
      "summary": "First-time PE prospect exploring how to start; needs professional-investor classification and ID verification. Genuine interest, early stage, no own ticket stated yet.",
      "source_excerpt": "Paulo new to PE, wants to invest via Moonfare; Keistha explained requirements, three pillars (direct, proprietary, direct investments), minimums; next step ID verification and fund summary.",
      "extraction_confidence": 0.82,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_503331650771",
      "engagement_id": "503331650771",
      "engagement_type": "call",
      "engagement_title": "Monit Sao and Kumar Singh",
      "timestamp": "2026-07-13T17:45:23Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503331650771",
      "contact": {
        "id": null,
        "name": "Monique",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Kumar Singh",
      "interest_level": "warm",
      "sentiment": "neutral",
      "sentiment_score": 0.3,
      "urgency": "low",
      "asset_classes": [
        "Secondaries"
      ],
      "industries": [],
      "funds": [
        {
          "raw": "Moonfair Secondary Fund",
          "canonical": "Moonfare Secondary Fund",
          "fund_id": "moonfare_secondary_fund",
          "asset_class": "Secondaries",
          "match": "alias",
          "confidence": 0.97
        }
      ],
      "competitors_mentioned": [],
      "ticket_size": {
        "raw": "minimum $25,000, additional in $10,000 increments (platform minimums)",
        "amount_eur": null,
        "min": null,
        "max": null,
        "currency": "USD",
        "basis": "threshold_discussed",
        "confidence": 0.4
      },
      "pain_points": [
        "long commitment duration / illiquidity",
        "tax / reporting complexity (K-1, PFIC)"
      ],
      "objections": [],
      "next_step": null,
      "next_step_date": null,
      "quotes": [
        "Moonfare Secondary Fund: open-ended, 18-month hard lock-up then quarterly redemptions",
        "Minimum $25,000, additional in $10,000 increments",
        "Tax implications include a K1 equivalent and potential PFIC filing"
      ],
      "summary": "Prospect walked through the Moonfare Secondary Fund (open-ended, 18-month lock-up, quarterly redemptions); engaged on structure, lock-up and tax treatment.",
      "source_excerpt": "Kumar Singh gave overview of Moonfare and Secondary Fund; open-ended, 18-month lock-up, quarterly redemptions; $25k min, $10k increments; K1/PFIC tax notes.",
      "extraction_confidence": 0.83,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_503313519859",
      "engagement_id": "503313519859",
      "engagement_type": "call",
      "engagement_title": "Meet with Alice from Moonfare",
      "timestamp": "2026-07-13T14:43:28Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503313519859",
      "contact": {
        "id": null,
        "name": "Caroline",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Alice Avenel",
      "interest_level": "warm",
      "sentiment": "positive",
      "sentiment_score": 0.5,
      "urgency": "low",
      "asset_classes": [
        "Multi-Strategy / Evergreen",
        "Secondaries"
      ],
      "industries": [],
      "funds": [],
      "competitors_mentioned": [],
      "ticket_size": null,
      "pain_points": [
        "geographic / residency restrictions",
        "eligibility / professional-investor classification"
      ],
      "objections": [
        "location in Turkey may limit investment options"
      ],
      "next_step": "Register and complete questionnaire; Alice to connect Caroline with a team member in Turkey",
      "next_step_date": null,
      "quotes": [
        "Interested in private market investments and how to start",
        "Discussed Evergreen and closed funds",
        "Implications of Caroline's location in Turkey"
      ],
      "summary": "Prospect interested in private markets via Evergreen / secondary structures; main blocker is residency in Turkey. Alice to route to a local team member.",
      "source_excerpt": "Caroline and Alice discussed private market investments, Evergreen and secondary funds, registration steps, and the implications of Caroline's location in Turkey.",
      "extraction_confidence": 0.8,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_503296070882",
      "engagement_id": "503296070882",
      "engagement_type": "call",
      "engagement_title": "Meet with Alice from Moonfare",
      "timestamp": "2026-07-13T12:29:42Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503296070882",
      "contact": {
        "id": null,
        "name": "Nicolas Méary",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Alice Avenel",
      "interest_level": "warm",
      "sentiment": "positive",
      "sentiment_score": 0.4,
      "urgency": "low",
      "asset_classes": [
        "Secondaries",
        "Multi-Strategy / Evergreen"
      ],
      "industries": [],
      "funds": [],
      "competitors_mentioned": [],
      "ticket_size": null,
      "pain_points": [
        "eligibility / professional-investor classification"
      ],
      "objections": [
        "prefers to avoid direct equity holdings due to political transparency regulations",
        "prefers investing through insurance vehicles"
      ],
      "next_step": "Continue evaluation; diversify over time via secondary funds",
      "next_step_date": null,
      "quotes": [
        "Referred by Antoine Fréno",
        "Prefers to invest through insurance vehicles like Willins",
        "Aims to diversify portfolio; interested in secondary funds for diversification"
      ],
      "summary": "Referral prospect interested in diversified private-markets exposure via secondary funds; constrained to insurance-wrapper investing and avoids direct equity for political-transparency reasons.",
      "source_excerpt": "Alice Avenel and Nicolas Méary discussed accessing private markets, minimums, fund options, diversification via secondaries, preference for insurance vehicles; Nicolas's political background.",
      "extraction_confidence": 0.78,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_502985851110",
      "engagement_id": "502985851110",
      "engagement_type": "call",
      "engagement_title": "Welcome Call Moonfare | Marc Oleschkewitz <> Kyra Thoma",
      "timestamp": "2026-07-10T07:59:33Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/502985851110",
      "contact": {
        "id": null,
        "name": "Marc Oleschkewitz",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Kyra Thoma",
      "interest_level": "warm",
      "sentiment": "positive",
      "sentiment_score": 0.5,
      "urgency": "low",
      "asset_classes": [
        "Multi-Strategy / Evergreen",
        "Secondaries"
      ],
      "industries": [],
      "funds": [],
      "competitors_mentioned": [],
      "ticket_size": {
        "raw": "minimums from €25,000 (platform)",
        "amount_eur": null,
        "min": null,
        "max": null,
        "currency": "EUR",
        "basis": "threshold_discussed",
        "confidence": 0.4
      },
      "pain_points": [
        "eligibility / professional-investor classification"
      ],
      "objections": [],
      "next_step": "Onboard as professional/semi-professional investor; review fund options",
      "next_step_date": null,
      "quotes": [
        "Moonfare pools capital for PE funds; minimums from €25,000",
        "Professional investors can invest at lower minimums than semi-professional",
        "Offers Evergreen funds and a secondary market for selling investments"
      ],
      "summary": "Welcome/onboarding call: prospect introduced to Moonfare's PE offering, Evergreen structures and secondary market; minimums from €25k. Early but positive.",
      "source_excerpt": "Kyra Thoma introduced Moonfare investment offerings, pooling capital, minimums from €25k, professional vs semi-professional, Evergreen funds and secondary market.",
      "extraction_confidence": 0.78,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_503258385616",
      "engagement_id": "503258385616",
      "engagement_type": "call",
      "engagement_title": "Call with Moonfare: Manolis Manassakis",
      "timestamp": "2026-07-13T10:44:54Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503258385616",
      "contact": {
        "id": null,
        "name": "Manolis Manassakis",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Ethan Dabush",
      "interest_level": "existing_investor",
      "sentiment": "neutral",
      "sentiment_score": 0.1,
      "urgency": "none",
      "asset_classes": [
        "Secondaries"
      ],
      "industries": [],
      "funds": [],
      "competitors_mentioned": [],
      "ticket_size": null,
      "pain_points": [
        "transparency / track-record questions"
      ],
      "objections": [],
      "next_step": null,
      "next_step_date": null,
      "quotes": [
        "TVPI is the key metric for assessing portfolio performance",
        "Selling in the secondary market can forgo future gains unless liquidity is needed",
        "Performance expected to improve as the fund matures over 10-12 years"
      ],
      "summary": "Existing investor servicing call: portfolio-performance education (TVPI vs IRR, secondary-market participation, vintage maturation). No new-money signal.",
      "source_excerpt": "Ethan and Manolis discussed portfolio performance metrics (TVPI), implications of selling in secondary market, and expected performance trajectory over 10-12 years.",
      "extraction_confidence": 0.8,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_502984804568",
      "engagement_id": "502984804568",
      "engagement_type": "call",
      "engagement_title": "Daniel / Maxi",
      "timestamp": "2026-07-10T08:00:19Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/502984804568",
      "contact": {
        "id": null,
        "name": "Daniel",
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": "Maximilian",
      "interest_level": "existing_investor",
      "sentiment": "neutral",
      "sentiment_score": 0.0,
      "urgency": "low",
      "asset_classes": [
        "Secondaries"
      ],
      "industries": [],
      "funds": [
        {
          "raw": "Moonfair Secondary Fund",
          "canonical": "Moonfare Secondary Fund",
          "fund_id": "moonfare_secondary_fund",
          "asset_class": "Secondaries",
          "match": "alias",
          "confidence": 0.97
        }
      ],
      "competitors_mentioned": [],
      "ticket_size": null,
      "pain_points": [
        "currency / FX reporting",
        "high or unclear fees"
      ],
      "objections": [
        "discrepancies in performance reporting due to currency conversion"
      ],
      "next_step": "Investigate performance-reporting/currency discrepancy further",
      "next_step_date": null,
      "quotes": [
        "Liquidation fee of 1.5% for the Moonfare Secondary Fund",
        "Secondary-market discounts typically 5%-15%",
        "Quarterly redemption requests with two-month notice",
        "Concern about currency-conversion discrepancies in reporting"
      ],
      "summary": "Existing investor servicing call: redemption/liquidation mechanics and a currency-reporting discrepancy to investigate. Retention-relevant, not net-new interest.",
      "source_excerpt": "Daniel and Maximilian discussed liquidating Moonfare Secondary Fund investments, 1.5% fee, 5-15% discounts, quarterly redemptions, and a currency-reporting discrepancy.",
      "extraction_confidence": 0.8,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_503054243004",
      "engagement_id": "503054243004",
      "engagement_type": "call",
      "engagement_title": "BCP III Internal Sales Training (Bradford Pilcher, Sophia Kolodzinski) / Moonfare (Global Sales Team)",
      "timestamp": "2026-07-10T13:54:42Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503054243004",
      "contact": {
        "id": null,
        "name": "Bradford Pilcher (Bonacord, GP)",
        "email": null
      },
      "company": {
        "id": null,
        "name": "Bonacord"
      },
      "owner": "Moonfare Global Sales Team",
      "interest_level": "not_investor",
      "sentiment": "positive",
      "sentiment_score": 0.6,
      "urgency": "none",
      "asset_classes": [
        "GP Stakes"
      ],
      "industries": [],
      "funds": [
        {
          "raw": "BCP III / Bonaccord",
          "canonical": "Bonacord III",
          "fund_id": "bonacord_iii",
          "asset_class": "GP Stakes",
          "match": "alias",
          "confidence": 0.9
        }
      ],
      "competitors_mentioned": [],
      "ticket_size": null,
      "pain_points": [],
      "objections": [],
      "next_step": null,
      "next_step_date": null,
      "quotes": [
        "Fund 2: 1.42x net MOIC, 26.9% net IRR, 28% net DPI",
        "Bonaccord focuses exclusively on mid-market GP stakes",
        "Fund 3 targets similar performance with high-caliber mid-market firms"
      ],
      "summary": "Internal GP sales-training session on Bonacord III (GP stakes) for Moonfare's sales team — fund intel, not an investor conversation. Excluded from the investor fund-interest view.",
      "source_excerpt": "Brad Pilcher of Bonaccord presented GP-stakes strategy, Fund 2/3 performance, mid-market focus, value creation, fundraising environment.",
      "extraction_confidence": 0.85,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    },
    {
      "signal_id": "sig_call_503586275561",
      "engagement_id": "503586275561",
      "engagement_type": "call",
      "engagement_title": "MF-HQ-Berlin-6-New York's Zoom Meeting",
      "timestamp": "2026-07-15T08:08:04Z",
      "direction": null,
      "hubspot_url": "https://app-eu1.hubspot.com/calls/3846368/review/503586275561",
      "contact": {
        "id": null,
        "name": null,
        "email": null
      },
      "company": {
        "id": null,
        "name": null
      },
      "owner": null,
      "interest_level": "not_investor",
      "sentiment": "negative",
      "sentiment_score": -0.3,
      "urgency": "none",
      "asset_classes": [
        "Unspecified"
      ],
      "industries": [],
      "funds": [],
      "competitors_mentioned": [],
      "ticket_size": null,
      "pain_points": [],
      "objections": [],
      "next_step": null,
      "next_step_date": null,
      "quotes": [
        "Frustrations with Zoom and meeting invites",
        "Statement about being a financial company, not a tech company"
      ],
      "summary": "Internal Zoom/logistics conversation, no investor content. Excluded from the fund-interest view (illustrates the not_investor classification).",
      "source_excerpt": "Internal conversation about technology frustrations with Zoom and company identity as a financial company.",
      "extraction_confidence": 0.9,
      "extracted_at": "2026-07-16T15:00:00Z",
      "extractor_version": "isx-1.0"
    }
  ],
  "funds": [
    {
      "fund_id": "moonfare_tech_fund",
      "name": "Moonfare Tech Fund",
      "short_name": "MTF",
      "type": "moonfare_proprietary",
      "asset_class": "Venture Capital",
      "status": "Live",
      "aliases": [
        "Moonfair Tech Fund",
        "Moonsphere Tech Fund",
        "MTF",
        "Moonfare Technology Fund",
        "Tech Fund",
        "MTF US",
        "MTF (US)"
      ]
    },
    {
      "fund_id": "moonfare_secondary_fund",
      "name": "Moonfare Secondary Fund",
      "short_name": "MSF",
      "type": "moonfare_proprietary",
      "asset_class": "Secondaries",
      "status": "Live",
      "aliases": [
        "Moonfair Secondary Fund",
        "Moonsphere Secondary Fund",
        "Moonfare Secondaries",
        "Secondary Fund",
        "MSF"
      ]
    },
    {
      "fund_id": "moonfare_mid_market",
      "name": "Moonfare Mid-Market Fund",
      "short_name": "MMF",
      "type": "moonfare_proprietary",
      "asset_class": "Buyout",
      "status": "Pending Kick-Off",
      "aliases": [
        "Mid-Market Fund",
        "MMF",
        "Moonfare Mid-Market Portfolio",
        "Mid Market Fund",
        "Project Flower (MMF)"
      ]
    },
    {
      "fund_id": "eqt_xi",
      "name": "EQT XI",
      "type": "third_party",
      "asset_class": "Buyout",
      "status": "Live",
      "aliases": [
        "EQT XI (US)",
        "EQT 11",
        "EQT"
      ]
    },
    {
      "fund_id": "cvc_pe",
      "name": "CVC-PE",
      "type": "third_party",
      "asset_class": "Buyout",
      "status": "Live",
      "aliases": [
        "CVC PE",
        "CVC-PEF (US)",
        "CVC PEF",
        "CVC private equity",
        "CVC"
      ]
    },
    {
      "fund_id": "cvc_cred",
      "name": "CVC-CRED",
      "type": "third_party",
      "asset_class": "Private Credit",
      "status": "Live",
      "aliases": [
        "CVC Credit",
        "CVC CRED",
        "CVC-Credit"
      ]
    },
    {
      "fund_id": "general_catalyst_xiii",
      "name": "General Catalyst XIII",
      "type": "third_party",
      "asset_class": "Venture Capital",
      "status": "Off Track",
      "aliases": [
        "GC XIII",
        "General Catalyst 13",
        "General Catalyst"
      ]
    },
    {
      "fund_id": "founders_fund_growth_iv",
      "name": "Founders Fund Growth IV",
      "type": "third_party",
      "asset_class": "Growth Equity",
      "status": "Closed",
      "aliases": [
        "Founders Fund",
        "Founders Fund Growth",
        "FF Growth IV"
      ]
    },
    {
      "fund_id": "kkr_americas_xiv",
      "name": "KKR Americas XIV",
      "type": "third_party",
      "asset_class": "Buyout",
      "status": "Closed",
      "aliases": [
        "KKR Americas XIV (CH+Singapore)",
        "KKR Americas",
        "KKR Americas Fund XIV"
      ]
    },
    {
      "fund_id": "kkr_asia_v",
      "name": "KKR Asia V",
      "type": "third_party",
      "asset_class": "Buyout",
      "status": "Pipeline",
      "aliases": [
        "KKR Asian Fund V",
        "KKR Asia"
      ]
    },
    {
      "fund_id": "kkr_ngt_iv",
      "name": "KKR NGT IV",
      "type": "third_party",
      "asset_class": "Growth Equity",
      "status": "Pipeline",
      "aliases": [
        "KKR Next Generation Technology IV",
        "KKR NGT",
        "KKR Next Gen Tech"
      ]
    },
    {
      "fund_id": "coatue_ctek",
      "name": "Coatue (CTEK)",
      "type": "third_party",
      "asset_class": "Venture Capital",
      "status": "At Risk",
      "aliases": [
        "Coatue \"CTEK\"",
        "Coatue CTEK",
        "Coatue",
        "CTEK"
      ]
    },
    {
      "fund_id": "lexington_secondaries_xi",
      "name": "Lexington Secondaries Fund XI",
      "type": "third_party",
      "asset_class": "Secondaries",
      "status": "Live",
      "aliases": [
        "Lexington Secondaries",
        "Lexington XI",
        "Lexington Partners XI",
        "Lexington"
      ]
    },
    {
      "fund_id": "bonacord_iii",
      "name": "Bonacord III",
      "type": "third_party",
      "asset_class": "GP Stakes",
      "status": "Pending Live",
      "aliases": [
        "Bonaccord III",
        "BCP III",
        "Bonaccord",
        "Bonacord",
        "Bonaccord Capital Partners III"
      ]
    },
    {
      "fund_id": "warburg_gg_xv",
      "name": "Warburg GG XV (US)",
      "type": "third_party",
      "asset_class": "Growth Equity",
      "status": "Live",
      "aliases": [
        "Warburg GG XV",
        "Warburg Pincus Global Growth XV",
        "Warburg",
        "WP GG XV"
      ]
    },
    {
      "fund_id": "main_capital_vii",
      "name": "Main Capital Fund VII",
      "type": "third_party",
      "asset_class": "Buyout",
      "status": "Closed",
      "aliases": [
        "MCF VII",
        "Main Capital VII",
        "Main Capital",
        "MCF"
      ]
    },
    {
      "fund_id": "leonard_green_x",
      "name": "Leonard Green X",
      "type": "third_party",
      "asset_class": "Buyout",
      "status": "Closed",
      "aliases": [
        "Leonard Green & Partners X",
        "LGP X",
        "Leonard Green"
      ]
    },
    {
      "fund_id": "qualitas_energy_vi",
      "name": "Qualitas Energy Fund VI",
      "type": "third_party",
      "asset_class": "Infrastructure",
      "status": "Live",
      "aliases": [
        "Qualitas Energy VI",
        "Qualitas Energy",
        "Qualitas"
      ]
    },
    {
      "fund_id": "kingswood_capital_iv",
      "name": "Kingswood Capital IV",
      "type": "third_party",
      "asset_class": "Buyout",
      "status": "Live",
      "aliases": [
        "Kingswood IV",
        "Kingswood Capital",
        "Kingswood"
      ]
    },
    {
      "fund_id": "bregal_unternehmerkapital_v",
      "name": "Bregal Unternehmerkapital V",
      "type": "third_party",
      "asset_class": "Buyout",
      "status": "Pipeline",
      "aliases": [
        "Bregal Unternehmerkapital",
        "Bregal V",
        "Bregal"
      ]
    },
    {
      "fund_id": "astorg",
      "name": "Astorg",
      "type": "third_party",
      "asset_class": "Buyout",
      "status": "Off Track",
      "aliases": [
        "Astorg VIII",
        "Astorg Fund"
      ]
    },
    {
      "fund_id": "overbay_multi_year",
      "name": "Overbay Capital Partners Multi-Year Fund",
      "type": "third_party",
      "asset_class": "Secondaries",
      "status": "Pipeline",
      "aliases": [
        "Overbay Capital Partners",
        "Overbay",
        "Overbay Multi-Year Fund"
      ]
    },
    {
      "fund_id": "a16z_lsv",
      "name": "a16z (LSV V Extension)",
      "type": "third_party",
      "asset_class": "Venture Capital",
      "status": "On Track",
      "aliases": [
        "a16z",
        "Andreessen Horowitz",
        "a16z LSV",
        "LSV V Extension",
        "a16z LSV V"
      ]
    },
    {
      "fund_id": "databricks",
      "name": "Databricks",
      "type": "direct_deal",
      "asset_class": "Direct Deal",
      "status": "Closed",
      "aliases": [
        "Databricks direct",
        "Databricks co-investment"
      ]
    },
    {
      "fund_id": "stripe",
      "name": "Stripe",
      "type": "direct_deal",
      "asset_class": "Direct Deal",
      "status": "Closed",
      "aliases": [
        "Stripe direct",
        "Stripe co-investment"
      ]
    },
    {
      "fund_id": "lightspeed",
      "name": "Lightspeed",
      "type": "third_party",
      "asset_class": "Venture Capital",
      "status": "Pipeline",
      "aliases": [
        "Lightspeed Venture Partners",
        "LSVP"
      ]
    },
    {
      "fund_id": "tcv",
      "name": "TCV",
      "type": "third_party",
      "asset_class": "Growth Equity",
      "status": "Pipeline",
      "aliases": [
        "Technology Crossover Ventures"
      ]
    },
    {
      "fund_id": "dcvc",
      "name": "DCVC",
      "type": "third_party",
      "asset_class": "Venture Capital",
      "status": "Pipeline",
      "aliases": [
        "Data Collective",
        "DCVC Fund"
      ]
    },
    {
      "fund_id": "baseten",
      "name": "Baseten",
      "type": "direct_deal",
      "asset_class": "Direct Deal",
      "status": "Pipeline",
      "aliases": [
        "Baseten direct"
      ]
    }
  ],
  "competitors": [
    {
      "competitor_id": "hamilton_lane",
      "name": "Hamilton Lane",
      "aliases": [
        "Hamilton Lane"
      ]
    },
    {
      "competitor_id": "stepstone",
      "name": "StepStone",
      "aliases": [
        "StepStone",
        "Step Stone"
      ]
    },
    {
      "competitor_id": "icapital",
      "name": "iCapital",
      "aliases": [
        "iCapital",
        "i-Capital"
      ]
    },
    {
      "competitor_id": "titanbay",
      "name": "Titanbay",
      "aliases": [
        "Titanbay",
        "Titan Bay"
      ]
    },
    {
      "competitor_id": "blackstone_bxpe",
      "name": "Blackstone (BXPE)",
      "aliases": [
        "Blackstone",
        "BXPE"
      ]
    },
    {
      "competitor_id": "partners_group",
      "name": "Partners Group",
      "aliases": [
        "Partners Group"
      ]
    }
  ],
  "taxonomy": {
    "_comment": "Controlled vocabularies for the investor-signal extraction. The extraction skill MUST pick values from these enums so the store stays queryable. Add new values here (not ad-hoc in records) when a genuinely new category appears.",
    "asset_classes": [
      "Buyout",
      "Growth Equity",
      "Venture Capital",
      "Secondaries",
      "Private Credit",
      "Infrastructure",
      "Real Estate",
      "GP Stakes",
      "Co-Investment",
      "Direct Deal",
      "Multi-Strategy / Evergreen",
      "Unspecified"
    ],
    "sentiment": [
      "positive",
      "neutral",
      "negative",
      "mixed"
    ],
    "interest_level": {
      "hot": "Explicit intent to invest and/or a concrete ticket, near-term timeline, or asked for next steps to commit.",
      "warm": "Genuine interest, engaged in substance, but still evaluating / no firm commitment.",
      "cold": "Little or no interest; disengaged, unqualified, or explicitly declined.",
      "existing_investor": "Already an investor; call is servicing, reporting, redemption or top-up rather than net-new interest.",
      "not_investor": "Not an investor-interest conversation at all (recruitment, vendor, internal, device/logistics test). Excluded from the fund-interest view."
    },
    "urgency": {
      "high": "Decision or action expected within ~4 weeks, or an explicit deadline / capital-call / closing window mentioned.",
      "medium": "Active but multi-week/month horizon; follow-up scheduled.",
      "low": "Exploratory, no timeline.",
      "none": "No urgency signal present."
    },
    "common_pain_points": [
      "long commitment duration / illiquidity",
      "high or unclear fees",
      "minimum ticket too high",
      "capital-call timing / cash-flow profile",
      "high entry valuations",
      "risk / loss concerns",
      "tax / reporting complexity (K-1, PFIC)",
      "eligibility / professional-investor classification",
      "geographic / residency restrictions",
      "currency / FX reporting",
      "transparency / track-record questions",
      "onboarding / verification friction"
    ],
    "currencies": [
      "EUR",
      "USD",
      "GBP",
      "CHF"
    ],
    "engagement_types": [
      "call",
      "email",
      "meeting",
      "note",
      "task"
    ]
  }
};
